apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starbucks-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: app.383140420017.realhandsonlabs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starbucks-service
                port:
                  number: 80
